### ISSUE TITLE
Update description URL

### ISSUE THREAD

**Issue by faustinoaq** [quimeo/apidemo#3]
Hi @papilip 

New Amber official page is https://amberframework.org

![screenshot_20170915_040436](https://user-images.githubusercontent.com/3067335/30474998-fdd510b0-99ca-11e7-873c-5606c979fae6.png)

**Comment by faustinoaq** [comment]
Now ambercr.io is 301 redirected, so I will close this :sweat_smile:

**Comment by papilip** [comment]
Thank you !
